language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
  - pip install codecov
script: pytest
after_success:
  - pytest --cov=./
  - codecov
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAJFSPQHWOSA7D7OZQ"
  secret_access_key:
    secure: "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"
  region: us-east-1
  app: Flask
  env: test-Flask
  bucket_name: "elasticbeanstalk-us-east-1-503452379697"