sudo: required
language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest pytest-cov
- pip install codecov
script: python3 -m pytest tests/
after_success:
- pytest --cov=./
- codecov
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: Flask
  env: test-Flask
  bucket_name: "$AWS_EB_S3_BUCKET"
env:
  global:
  - secure: J/GpRaXO9JsP9Dd5z08l4prs/OF9Tv4st3269i2DIUbspCw5ZtRaOdNDdu1RcxQMAbEleReFVh9zmmXtxSop9tAFjTvM3SxkIst26fC0L1kjxKQvWJuyJCTkSAlIdFyf/mbVC3jiTkoisGax60r2wXzAXbjyaMtxtNe3CBLkaUpHi4QPAMmjg6Q8tHAzHGhFzVKmM538UfMe6jzXziA4P87grTL4TNKr5D4PjW10Yj5R1fhQ3s48IsHNn2dbkApPFZUb/9OLF7JkfI5/j6rnioVrmOxrpgDGfO7deaXggWOxlVRWffs+XDz8bEw9AxMZsmyxc67WfMACdVWCcvjgfDaNfxWbqxXR89MKZ/xFUqee7bTBFiobPGQcY+DC0JmCcX0yWa8qVU1xBQjpWTU6Ju2Aod1ckmG6WqCWu8/0TNsyGD9aHsPjfbnC3yhXAGJrqCadRDZgh3ScHtbI9tn4MhTdwDj1TGpGqWLbNPn9BaH3DgfXuajKhhJO7zaCypNay6JmKPhK7wssCquKnbT6dRF5SdGZNBhAp5V0ZVqXBAT2SJELd4bNK3MJLnjpfGgHhMyqXAdXLgR4Col9sD0xNR9vO+QdYVL35Jx9/9w3wGS0YkODe3ThFmEJvdWE+fxytbVTaGauT1M8a05WLNvk6/dG29LUwQE35tld39Fn6wo=
  - secure: fW46YAX2/lTC0TSferk/AqS4pYXAPrgEhxBjRIWF6288fSr2kcMg908okbq14tlaNfvEqPvhjHr3Nkhprm841LuaoFE0frOvIsr82fbksCtgPuJ8YUCbW5esqNXIRNqY3BQcm/Q8wtHdzDwhhZh2RhJDPKlbJAonoRv6BHPDt53GMaK2qZjknZuaYXFRJHUJgnNzCipGxlFYw/DmL2LeVYiwpHTsFFepDd9I+JGEz0zUzLpcuvwW8XHTDlYZYHnrGbQZPToK0uYuflfrTstw2BWm4SL7rkjYlte4pg/8+q1xlN3Ccm/ArfJGEK6bIVThfypaBtuZnQ2QPhRFqiPBmg3uPvAG+20We8y0EDCSaI3DvbYHh9nYOVHoRQzfVCvXVQKcUmqlenJSNyxPBZpBPAKiCtTRLUc3GxF880y+Ss8216rCjeOHQ58zyLH4zoP1oo82QiwtPywlZBSqxUI1MBBa2Hgoep6MCuK4eiMOJxC3YWlWTCsZxbUFnCK/EyRu7hJ3a+hIOYxgVRoGOrx3wvF77L9m1pBKNZkvZg8cAif+rbwA/skBIu/oNNSsJm7J+Rt9cYT4m390bumW5i0f2baAgeS8mHKAQZzZ/7QYa8EF+3XJzJaTZCMbp1cZ+JNLx3iJ8OSM+PvNgZnORdsfeioFnVssAkUYdKJvaEXqwl4=
  - secure: PNo6rOMVRr/3eD7g6FQJSCtQ/1WGLAh+qutIQ28XFN73MNQwcpQ6nDJtCTUkAKfKLWRXGWgeFoR7nxH6s7CpwuBPs9dnx6df9zGkbZxmG68DIUPhZORaRph5jrAqyT4+nfYiHt9q2AGneP4wWjJv//LuEL+vvvlbxQTsuKdf56rDzPKs75VWsWIywOiNJ5jeVUclVht6d65Lrs8f8R7QSB0eP4MC9ehWuAH4GqdwsiFVSLB8+H6PH8pO8wf7TI+yvE88mn+5n1C0AoccbYz/KitW/JfySh60BQIsUixBkF57AYUEjoGNRTmdWDLOvAJEqw2pfH5yTIFEOSc4wp/nD0VsKLaL1tDjifmbT58fbTQBcKDAlXI0p7w1pKql/v3pzzWK8hBIMKbqFYxjppOT8+OckJ6Rcm/GpgIKE8j8ca9Qc5Ngkl3a1D+SGyQ4l+5JWN2OEVTA95SjAsVLKeGFaW6eqGEX3DBfA5/MaHF4wdbT20gBrO2n4fqJ0rDNHCVMU8mYk7WLqFnCEA8AXOmAgWLLuibr+5YHAWitg0GJnb6jUseB3hX+SREEwzOKgZlKSfYvWErbPp9KrxaCitMz4C9q3SiQ8AsDO1cO4RaQPxRdxEfFJeBxgNDsU4+oCINuON9tnhecCMi2roPqEYThpBLijeXImoUOLevQ/szc31I=
  - secure: u6/9XgGHVbR1Rq+JtCKW1A5JsAoJfe78/h6A6A6nWzelbVQpILuJmWN/FJAb20oQsvxiuo21PeFZwu3aEdSJaYxgDnfwnOYPQJsEZ2eG1oEJq9NmqTEAxI9qIkp9cptZt/8n9kAJAQMjMDFZo7UI8WCwwk+So+FbJqYCOUeScNQD/HHAGbbtkrp7/CvdpW/+BZh4XeMxpvmB60aZvoSpWAmy0aDOVEbMnEdwgjJGkAx7G75r5Aqmt2DKAcEBf9uYYcOH45SSWYp9PA/ucvnitTyicD2maRoIRx4Mk8cQIQ/kJamVf8T/FCsXx0NXGAQc+/Wr9uHCIKmu0jO6zSPTZI3Pui2RGTdQt5XQIM8b/YCQfnqAPNJuq6IJslfJInAt6Z0TmjTeAXYFknhuJk/XAln3luNcqhxWUKA1QVGT7wdFrtoNoaQ/yb1/oS9/zlhEVgVCE40fKFTzN1vf6BTcxDvUzd2N5R+dErr0UGoKWfWMeobCl2Gqfmpq69m8PeYbkz2IXmvRUkODQucuWfgGMw8HPr+sTRbVtWJcrld9pQRDm6oJU/UKujtHhNPEo0U9DTT9yjCYIbuu6LGhS6jK9gVTOWIvheF9BlUjmgVvrgj1lgOhTNvM0VGye7NDxZmXqxg7MGMXbsIX7lTxdVfKMXW0nxhv9gxpTR1YFhNmLH4=
