sudo: required
language: python
python:
- 3.6
before_install:
- python --version
- pip install pip
- pip install pytest pytest-cov
- pip install codecov
- sudo apt-get install lilypond
- sudo apt-get install musescore
- sudo apt-get install xvfb
- Xvfb :0 -screen 0 1280x768x24&
- export DISPLAY=:0
script: python3 -m pytest
after_success:
- pytest --cov=./
- codecov
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: Flask
  env: test-Flask
  bucket_name: "$AWS_EB_S3_BUCKET"
env:
  global:
  - secure: dNT4u8aeDcrNg4pvbd5ylrPFoh6T1Qo/IJKXp/hCkTj7WG+rzMmMZMRhdPiZjS9b8DypygjmOXPp6qE8LiRY9Ob3j2rQTX+Vq40q5TJbYSvxG/hV/t/uRQ/0LNNVecYVox6fePf6VKhaQAYJ3U6rfmBez/V0lF3wErGyEeaz0XCYpVseVYGSi6cv0k82Ex7qaxEsMmb26MULlJLiUDnsS1L5S/BEag6TRkWxxTiqHs8AObvYQjfuLKoLMdDvAr9hxfSO/6yZzwZoqeV4/T4gS46rKqXUZ6pXZx4goIj/bvN7lQA1zSQ7wJ0XgoarJ1US65kfFQSBn6zmECway7GWgVKetI2LpEj0j5v8BHXy3dyN5IFm1gBYg+Sjh0ZS1fi6Y1wHHBj0C8JqDd84/tTN22JGSKRItPs+Hl1UnHPdHV2YNDXbnd9P35PRuq/ZeGV8Yd8nVIse1bo0SwijE3wCT+RCW2ACvYWXQrDNrojN6cwuVKVfjYH6oSlbwYru2vbCbQE9HKC3Ga+7qa5KsqwNLGVNE5S5ZKF3ePZvgancTRw/qb11ytp0dWD/9KQQOAAzCgSnuMc4HgozfgBBxU8bcTjFU8ZJG1dQTpNkGD4FbA2m20cPUaKoeGWcpdfanIFfyNViP+P/PplU2V4xQ2kdvWVFZIy0GqPhvGb55E6/WPo=
  - secure: PoAOm41eL8kb6Uf0AsMsApgfisfXUr709EN8uPPan+Gsmt17bk4oGLkx4Q0VIWb88AcJjM0cD6r2ocBzWpB85v5+wmXrEr2N6soqLuYkGyd45g84FoAioK48ROG+DhQgQ0Znp2mYifkh0XXod0Xl0KxQor8tg49k0Vr5fshBtHvDeAHLVBK1Qr0kZ46W3hwGtiLaQhclVp/vh9VHzCqFKyts8rHJZgFFg+hPYpADtxmJmF5Fu08Etae0AAxqF2FjQB9SueQy0sBhIBMKDf/ILLPDFuepvskC+ybkP/aEdKbyxkH8hC/bHEa+ZFLOFVb0/Ld+qeRMvi0liZSWAWOdcu651GL6Z3XbIxv73W2xcOR1Z77tx0f369r+bGbUUa960DK3g/KKYbYESJouOvyE0QlUxysoE1vliMUZJQkRmqrY2d4LHMek1W1S1jAgwL0r3kcJGcXOe+87ZT/72PkkcQoNF6sgYBPwySlZ+u+6voWQ8xjMIPoM0F1loxV6Xi2fTfV46lsNfBOCOkM2iDMfrc3yOSjWF7LVqTUhqRhPuGVkZkrwmqkurG5mgcUN7pEdCQrjEpS7X8tqLOPlyt1nskvnB8GIvauAx/SqNX236IrxZE+sC9/GjMiIvxzk34hAG14Z41mfmaJaSWzSpikAasNQMcz6hY3s+h2QqvEF4oQ=
  - secure: R5mmj6gAdlPqxd05WsTQkRfxvu2AiazEBO1Dnzem8018g3zLdDK0l9YyQ77Wu47QY5FxzieSzs83vIfpNYxVI+jPRJDfaJSVMSDiWxQrEbbfe1k89ierI0JB0WUrvhaKWtT7w8ZFc9O6pQi6KYMOmZddNwfZWZSn1xLrlaFdR/Q6xWj4AXeLvxY7f3WifN4IHihEhKWjrOv+mPUtIu2nwAFlS/dP6Fyqw4EggzX0MUiUZUWnxmeU0WxeIKS5wF45NRKTpsk6AmmWYFgs+I3D14vj9RQ0zQO0TSIVDt1k45QvflGWd0drhZg12mzWwTe9B5c1VllO22z2jfxqpC3jna/8g3FeJYrD0b/Ih+urRxBTlSu1F/E1/8FGiGtyLXaZpm+csEWH6v3BABVC3svVYUpkVDVtCglWKQ75dWhB4ZJZyhJ+lRHjDCKhAjWuB/+1CB5tvI/n6RgChEytzIEcTdP9Xt0V8y2WxAwrouIJMv/7QtPJYDvtAE/qVANFvMi2TsGhmMEkdN+Ck1Q0MBpAriHXuS+s5ytGyVhNZ+kQGtNZNVwtGI/0gr6bbiG8D1gHd7RBpMJCwhzeQLbjCw9OLG/48BeFnGDMIoBejbmxqqxWTDjz6WAIPFKzIZkAVlb1ioxmekC0OkwzJ42YmNEJIDnzg4r090Nc0r4ZyP1nmU8=
  - secure: zTsNe4CCZ1Q0M4yWRmQH9REXMSrHTvvUCHSx77hLE3R7V0LzVAdRoJvb0LkhP9xMcG2gC2Q4wBJsoQm9VNrKrt7uqYdnfkA8Gh3VocaG2/FSJij2GufqX2WqG0JqcUuvMPcU9cfxHqlDcZ7AFpThrqWuXa4JfpOVHdc4uok8kZC3UPUI6X0VWbkWW0J2fbgHR4jebJ2JLy5n2YT8xPlK5DT3Q3g/8UCJjY8CPffsZGMWWJJW5dpWsw2wAUmRK0sNXxWpdPKWQ8tvyul6T278vxyFRKF5ot7VFmkDC17GHih6I1aBN3NotGI3WgljqHeryEIy3BknLe2IvbRmEzRvS2raYzbf1+auJng8s20VQA5bxUiex2i35esixF3sK1MHUOnWJz7fg5o3T8MP+YYYjaOA06QjVNPPulynjoFt74vB/wC++I3Ji7PUo1tF1gpkpgjputkH+vesiZL+1jKXr5EgWO1lLerFnI1S2uFoma/TdwDmzp/r2s8dJFfpBdinc442TSC0PI+2866G1WdJztFTmVECdiM2aLJscZ7DPLnGsVbw3Q3Ch06sR4IAF7PhT8SxXgpdE2XuiEUnEgAD8ZcPP761ctIJ4y8oWwMmnS9yNtMPDv4i9EO5bEWK/mVqOsaAdYF8+HeZucMLwz+/6umi5/KSwVhUGtw7691qrJ4=