language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest pytest-cov
- pip install codecov
script: pytest
after_success:
- pytest --cov=./
- codecov
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: Flask
  env: test-Flask
  bucket_name: "$AWS_EB_S3_BUCKET"
env:
  global:
  - secure: nCNm00oMRB4oDxUWjBO9+jDAoulvnPGe8yzKBCsAPMO4WtY5CZBbWKBdfdFSds4GbejEXvol7ejelA0Z5hEjcRk9P1xonA9Zy0c3QPx/9SZGZ0MYSO9VeNFISu1BO2OTdKu82CELPc4iXo1cK+RdJsXvWLovPtRfAjdvJazia3FU99ttiQnM3b7L5z90Pu/a1SQEA6ptfQ8Z0XXXF7UreIQnwO/R30U/K9n8ZcZynuTuu5eTrL9haCOBpHIUldZ1CeZQk4CIOZPwhE6vZInCwuzzItQzGSwdRzumF4IfG6yqDXugFKwz2JrDsiihh/qZFIIxqGvTZ+cmCp/JOuUHr/ZrZ+0KntJib5HNgj8JeO1pnqHBIu5AvAQNqL+aPqoBBtki9oY5MqXHKVpxbGaX7n/API/G9AZ0G+12rdI+tRY4SwF3/oDg0TIQ7olWn8k3ftlUO+2lqPzK7AvqKnCquJhHq5BFwh9E1RwP331WSYYXNWzrdjgB+YLYR3dUnw4bXKsiHHPrHwpQbU0x5IIJ/5S2+g0R6PPKuHpOSDybLBwnQ7MkovuJ9IVhPu4OrR4po1neHkg35OVhdIPExKM7fTh+nspWeo8vHF2+Y5vNy5zys5XDpbQ+VF83xvrD75T0Fgoh8KlgrK1idJVUiX065pzERYXKJBn0UsqKxccxrGY=
  - secure: YaL2/LptzsrSayvKjkw77u34aqPpf4R1KjwHAEFmq6k6qEwsdCM+0xGPp71tlyQhvUXd1IE9WY7mdRkWc5z6YWDf7aTAN9Aq7e/OURa8bFmcHrG/i+nmm93m5vED6EhvpO6pCTwk2xne73wnasShFrr/z1yusS4pwkQARrBH4ru3RmfarkGdEj97dcn0TrSS7S/PMMSBQfJsM1OH7bh+fBQvxun708jRZf9fxbdbSbBF/hLoUZ5LE90rn0+YB4WP/BVhj3y+CLe6Iy0ktGLL+hYFeuZQ8Tl8L7ByMs9FX6lVrb4jBHjHV9hTAbZ6Oaz4hNbAdsXb1gSGeVWlsh6V0HLtFAXZk6l4l5J5bMnpFL2xo3XneLhyN2XblxihuXjI05GP7xi3fEPmZY+z3NgWoP/OMowRV0Y0V1Lro5wQoXYNyKTKwTGSKNuKrQPSAGzruXK4WjVLZ6K61EjSyIPbd28zORKaPe7ypGs5306+nWpFg90ihlUFOb0mP7Kw/JaMdpC7RY2AjwcK1GCTFadcDFKrfRKUY7IBpX+gRz3GwLPt1UaUN9D+ZKdXtGatYxOIqT3zN+Rdj5OxS0lTxmKXualyb+mEeTzEsys4G7A8ZZsftVLZQ6fPn58N65+ia6qw2AxqPYqGQliMaFkjx5SzhjrZtkt9oCAGPFCyB9cd2jU=
  - secure: iVRZR4CgPdtCevj7YJem5OCoDvIUzL6+uyCcjPjZVww2Z0uKtHsnKK8s9uYpMDqjO7Z/LvwyTCEJGShobbTjHjWHI6doAtxdJl6A8fMIAgZjeeFO+pywLzpG/3zYnb7nURq8QCEx2B9GaTUwuJ1Jgi0leWsFXw6NX+syFDRqhu6pU51Cmql9zcUUU62usV79P88cRD1P14gHbF8o0ojVwArYK5nMU9xlbCbbEq6tEciIT/YH4Rm1nyiqTkZn7PN1dqRNuT45zEZm/wZf3EsPM3G8EA8Zkrg9J2gb9Sg4yB825JcDeJTblBjT+DnMjUU6LJTehpr/eNFX4VOYJvf/TeJN70y6o/cRd90OiqlTuXvD1DCHLE8qtaugYNuiHh9HliOYDjLkUBnjo/Sd9Ring3AJ/1/2YDC98XuPsvLVcJe9SKw8T7T6QAwQfmYyLgio55aWayKJp9nKcPB9Mq2f9yORNAdHXFMzc9MN4QPAp1J2Z6aLAYGFyxZyFbE8lCagwgS18Q8suiPKyU64t3KVO2ed0ot8K6VeGxaaivpB0klMFcit+if9YZcTTDwcPyhDSVcIAOXmEpmrUJnzr1z+YaXAHbyfEl4wV9cEc7ftyuYuMOvaixHl9A1aq5WzWihXQsJgLLJwnj+p5LvQI9pkBnXtCGazC2gWDh1CF6ScHTQ=
  - secure: UADfZmm+l56og/D2oI7rmlJuRhMdx5WuCcvCheMTK/b1MOUcK2xjn19dnPafX200wF4p+UzKCZxIWfn2TJNkg1ZhpkMlxcXMC+uHQcDlVT4F1aoJnf6TZQSI0UAXO1o6VdTPeNItTu/tSX4CwjHgNOEcPvHIw+bn8b/qEsaxlLvxj602ar/JlijlDqmiQCj9ZfKbKClK3xW3Tiz6SXyACrz+nCb/FVqN+tRJ8+nZn2oY87sIA6TvNMBf8aUNdyJPj5Wom7WD4/quNK1ETYMg3x7ToMLvVXoZYfW/hdMu5V9LBE1khUUd0GiXksef72/UPizgODDm1oz/obTafBroxnAobgyEI51549L+PwKfnMk5Mzj1zzGofeChgQzup56A89Ym210eNrvKHRp+bqCx1MGysdVcB9wcWbQkkqgu+GPmyRDZkMSgcaSBiSCvnA4zyQoffiYQc3vY+A6kxnMVrS8ZbOR7xysRx5PAHKjsVv4/RPdI1OxWzPEF9N9emcAFoc3YBrnd36A70/AnIiYo8+Zb4R9qQuWbEW3Q1vnvIxQRDAITo1Yi2qz1KMASO0Xrm51QDX+t22PHkDGoqa1kRzdp/gYl/4lgMVbnB/rCQgkFgvzp1KI/6MQP3nTrKlTaXpgAL/AFLoLfSzZ47fsjGk2Qz6etOAEfLJjOCtgsX54=
