language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest pytest-cov
- pip install codecov
script: python3 -m pytest /tests
after_success:
- pytest --cov=./
- codecov
deploy:
  provider: elasticbeanstalk
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: Flask
  env: test-Flask
  bucket_name: "$AWS_EB_S3_BUCKET"
env:
  global:
  - secure: i2tyyGya1uQ7dqE1a63Ho2IVQdx0lj3q9Xq5RFsooilW/x2KJsItV5Gr9SC6X7rm4vDABWu6EgkYoKOKmGeO4BdHl9MdG/4gDZOP2dZoyyXQ5P0+T8gVzepdQ+AqaQvw4EhGboJbtaLGloH7psjeXFxK/BLHwMUnZHV/9c+oCIZ/DIFCuobDfWx9IuPAsMU6eZPORpcD4/MXZ24kC09hkTEkqPPybgmGdKN68h2Rs6ITrDTUVdZs/Fh0LrLRXLOWOSHMoRhBbp8CRd9FvUfWbU8ahXfcj7H4BjYb4NslFR0KrRelNBb25nLtfDtpaQ/cH9jxGDOqOg7PWRHqC59mgrTrA2kfLduU8VjXyvYB2p/zXR5+MpVdTWVxB7lPFhza8bJzROgX05Txa08cdXD133m3L6cJC67T8AH13PrBj10jCl3NX3F/GMoPF8aQK14oR25GHjnaTPlchVKy2d/PM8gXoXZSlPSw2DMM5u4aDAuE3M8lnHtSQTkb1xbaMNm/en/H2JEtCBi09ACe0sVk3EoiHwHMn7AANDOAVB9H6Gbz7ltiJ1tACWqIVYu6B/rNtnWyPQ19p7Vn2xFf7UOJbFWhWrBxoCfsWUwDqtIpG8VUAWp1tzYGsoZJgmXBFjOwqjtE28mb//8UGJVrwD2oiCUbTpWG9kPBzJKjblLJgew=
  - secure: Z6lcl5KvQon0GkXaFAn95B7YtzdpiRHamqQPzwJ8hD1QsY6lKhxbDd3CLM4ZLTE2M2ezsmFtpACL33eKMFnd4OiLbhzt7p4eqK4Ct/njwZ2HfTxrMHuQBybRWjb6ZMRTRy0q0swH7AV6HwtsBrNs75Py++DBgwMrXeMCgpQWZnA7kM3tsDxf8hgBvxFWFVbOtGkI1B6x8xp7nirVdAHjc5Icox8amCmsDKUvZchwEnGmwcmTU58COnvV6A08W+CqNBbDeSd/aCP8ZRLHRXCHJMXxCUVlLeXMJ6D10neeii6QmygDjEtRYaXXk9eseZL1hBHv3qr9k+nBVfGthZdI/m5o2qaLYnp2DbAVd9M3AaYmh2rDhRd/7B0Ch6t4fxvIXhS/kDvk0Te4Q/0qr5EsMWvZJYRlk+UJCSL06qIBMhj1h4Khjp8rvzwVqxKJDWsBp0HcZFxnBb9rXQaq19vqn4LBdFZ/4qPmVFanNUsKeJHzITkxTpaR2O+LqFfeXXK+kwhRWGWYF90xfLAbuP5DpcdESfppHtTOqA13H3hhmEFmDpsBKcmQrp2emgfYorxEcuc1lYwul06Bxi0fvKWBBGNYxKVClVz8EBYqpRu+4z8fEzbL5Nu5L8BraWHX3aAR3uWSOM6HH8sA349rMO/UvkUPIEZDaN8+P2Cn1vixqso=
  - secure: F+kNjJwlItX6iWQ8qWzxN9NFdl+07JtG/491GNDPpfrAINif88bch9djbkr165bkj094B1J19X5qekga8W7h25bGi4Y5DTNMchuz08NWPoogXUZisZDfwxiymngbem7XAjg7Ur25Q4SqZLVhjut8lmhkm1jWfZqDlJVTXdntNFclt5OgMI/AED9UBZNrlyIAw1vP6fTCUWmbGf3d2x0JMsX2w0QGJ6GUoeHw54r9tALJWznS/aTB9cTeQ9lbhh6jCK6CQR2bILt2DaEXcgW0cygvCdidAjZbM6rs11pymKJ9D+wFmvLNrQaIcxnRfbKpOYGJhXrrkvtvw0JMIGB4ylUocWzSqnhjX4SA3QirnfA75y5laJEGhS46RNGbrhURfEZhcEAzGJo3h/cGU1+v65l4/mrnLFKrQ70lN1XqkK7fp5QEhDroZMfBXFgYF8UgYmHzS2ttB9VOkZHTVC7BSYs5aKnLK7r/cWovNEc+S0QlIhfR18ywF2A3W6k8IhnEtOav48sxv4mXCJpwHpakyv/GaX17JCJjgcn2YHbIGotMH5urhvMLeo5o2DUsfUz+s/dO0geHfIiNColobW5K1CVrURoJqPyaCWbcBlD198Qq9IbtnSlMhDmMB5UTi3oHlQ9B1HwOzmEweKPCPFOFGw7NspmzUQHwbmDG8IygSkg=
  - secure: YCfyBA4AxE8ykYdOX24ng0mCA9344VnPdOBepXPRdRE9jUGqE4OWLHeir7SKXmaphvDhlAmWYY47zfOP0CYMFZ2pfxipwAhvX6hpz81etKXjC97wJtNI/NSpfT44Di4QID+JQ37+4EKXL97f/hLJUwGs9l1YDY0FMMWBeoPSBfJXPM56HouQkoLekSIMRX9OIvy7PZdOhx4ajspLyQE/jCB6FMq3g3dM5wjjOLUiZUBhGrEGQ19RiUYdyVOvLijb4+QzWuJpPGPV5Pb8iu14pAcfnNyNDkVlo3wBy5HHGxzIxJDn4A69+EXVd8OWLFnsDstlFqXrqCOpByFAEzfSVezUOPCr2t8vbrIEUaSoFn8emCR1V9OP8ZC0i7I1T7bdgKo4OvhJG9ojNd9tbz62lDVTx0Fugys5AZA9wplRj2VGzX5Jh0DbxO2k896A7dQfoJWR4tQV5JnW2EbMR+OWJUYSyyFFAoDTcywmBS9IifxTEImoAYhVb2/iIEZN70V/8DGdxyd9O2EugNo+oCAJk3Pj2RwEyI2HPQFPRrDWp5QACXvdeaEKWG006JgFfFRtw/CZ5BREWmURfaIs50BOmvFzlw4ZcuX5igzKNGx+RE/Lq7/XCRrgyeeuJ5T5S7csSe2bRxdBIWUZobTb9lxQovmKcvxa6wc5tF8KSxti4Hw=
