language: python
python:
- 3.6
before_install:
- python --version
- pip install -U pip
- pip install -U pytest pytest-cov
- pip install codecov
script: pytest
after_success:
- pytest --cov=./
- codecov
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY_ID"
  secret_access_key:
    secure: "$AWS_ACCESS_KEY_SECRET"
  region: "$AWS_REGION"
  app: Flask
  env: test-Flask
  bucket_name: "$AWS_EB_S3_BUCKET"
env:
  global:
  - secure: GLmCAggKRlxjOmq1eAgtiBygWfYnyKS8w8gLL0ETWxi3BlPpUaqkRiBZsSVIH0pIl7qIFkXGGc9PFBEj9XYLGTwnsJtMXyPvh8eXg8i7uxIR05e2U83sXirgVqx6eYaORWzE+mi1j7QfQXQf7nuFcNoIpmtd4rRPJ5Qh5n0n2qeRkRt8fUPQ77lAlus/D28wUUlR8x0dwSRUMFjhRwvmB/gRJ2fERNXRKlU4scx2xFocfovzOCJ/Caohzsw/Wm+VrEMxD+yflzIb/M8sIK03XwI/MIO0fAvaPiZ63/5G6m0XCRoiBq1uKETSKv/8gzXRgg8inxPOwodL3s77bt5tKdzQnePx1TENbbg/8dL8ZCXK70n+2K5CLMGx+KAWuuZTaGC1fnF4xh/Rcw3q5I0l2BDxFFhb2Fz0KxjZuFzMX4QM3AIiQvCCGcFgKwb6VnL+PJ3Pevwl8msy6jbJNcLOhXuNfhAmf3NLlIlb15aGszmQTpd6E8LOGIhGl8P8Oi4kTrvyDg2SSLMbBNEjk1Ap5mJfBRsBYAAB3W3WNm2TmnELAOdqOC7IP/IrdMoCBTWcHIZcnDn+BUsmbUG1sP0UyzTltpB653d/9dAbX84XaH+O42JN+zNNY4hTATYaLnDQnydrlck6dPXz4Ww1z2IAa7FnBxeSIrYWoRedaJ/ehRA=
  - secure: It7qRncdDjku7uALsgErw8wQYnWY6vyaijixJy/XpP05Oiz47zy/ulVaqY8OByw4i+ex6wMQSy7aAdNyUqC7Mu5dWlGYs4GN/SRn2Uos9YTv6z10yvZeZur0gKfCYmtdGnNAIEBT0Vn7x2H1S7CoOJDOJgb70WkqOnWrvyhoEylV+6PAL7bno8uOQcsGB6V7ZRq8hrbyeghv+gF7Vrhy+q7l1zb9uRYE5uhBEFIWi7hQyerLhe2CN/2p8O3dI5KJxJQoJXLG7C5km1Qb3tDgJn0Jbg5gF1bwvapHzpNFHSFiAEg6cny8Je5EXcw2oYGvkxH7YjYEOSp1OUG6p8NKEjXQ9c4rPE58fyWGBHdzm1xfvEq7p3u5fVDzt9ILmBJSC9MzEtw3N0bgatef4jaHxOL9SjL8WY5IoPO7SS8sxRPZTX0vxHTnZmzB73abVTK+1mY+Gqoa4iojd3nQ/qUQnq/e+ypJMYqG4zQl5wd8HkNhF5GjDF1358vHxxoLM/1CYhZ9pkyex9dnBXiBuhr8m4bB6l4fo1E4NGyx8yGUXI59q2wMTk1I6yR+0pCGAeMiLo3xY5z5gIqOOTanAn+1ip2R59i2kIq4TIPoGgPeiS03goRvhh6JOaXvviHQbBmkQOSBgvcLZzgSAarBpORqAQAYIbRKWrwFDzdI9QJ+nNg=
  - secure: VY6w1S4haB8nqqi9hn7qDlH+TREDS8H0jjjJZWwLvY6m9S6J++LQrRI+OkcG+CV18Jqvy6Uk8WdZmViEW3Dl2bph/TJKVpWgwv4h1ErkfTaP+JnYyiuw0q6LIP8GJGay0SvpkVHeDehaMaMD7ApSEQvsOY1a4r4ZKC4fTl85roCxWmaJ82+/bhaeVmsEN5255SLM6u01ghKOuEE09FxJN8qpZ7zR1rzw3WxQDtA/jwGLw97UoDDVQ9ELqmCXmdPDtoxA2eb3HVBAwZd6AEp10tVhIJ/OcU3Q7nTOCgCOTbmCOG7MeyiuBKJCfhvXg0LcIdWYoYJ1MDbmpnIx8b50jwIAW4QuYMLQt+COBKT1R8p43zvX5H5RXfNdrArhJo3nEt1MqspjLHa0GqniUZO3Ij47Io+n46QYGgivDxTicRUmQlQM6wXSqWCgcDB3bRx6IDbM+loGVNN2TmiDk71mdJ4oKDtkuU9fg/622Z3s6aenYo9Co1H5s61cOQv16M7X13zMUZr/vgrrqzqdT1yLr1BUoynHghhtWti419FG6o+QhSQh9osluSBXCZZ5GisiwRyZVdijEU28pNVcrhzHiNFKy5ZfKPbJnr5Elnvmm68UXoisluWBnynjvnOiDah5WWIP2b1suTWT2pMryb2V3dMN+LJuaA1oRTFhKczZMfI=
  - secure: fCnhZ+ftrSnc6CpR+Sesja9EPcoG/PSfFJyGsnP79vBJ389RZq3ksllokSy4eX7t6aWsY8LvHZEZI9ORIAvi7gMd70tKwNxwqYHl7qW9vDmZ7i6UG75CD5A+XkEvotiQFaXaHJqIkt4dqFjtUfcUNGREe1SG10nPC4miJnSJeEjvn+3FC1B5OCJuxx2F5vT5TBMzKdthOZRT2zXK25EpnxzSiyg5dY0mrXW9DOsWlhTD44yFzGb1n/2ssAxcIiIJwq5n+G5iohaH1OTlik/8OqP1t1ejB0DyKFiSspEzKuWLGJmypgeFZyZeNoYX77n8/xYhWisLAP7/DYORfkUQofsVpJC0wjqZ19ejgtDR/B8lQ+eUZgZJwchkEXyZwySICdOH7E/vyurPDn0XgferOkXzBJzdYnH/vvEsH2aHd2LujHXcd4Eudnj8dKtEUzVhFpoPW5JzNDQxp3Doqo8PcUI6TIFJPOVfpCzVPsjc9FcH8nK/qK55Ff5B/f9YziV7cY/maiRy7DALslrbybauz1WRKDGx9nGGO0bICZrY3u0kinJrfrrxqKghs3h1NlDRQdpxNX51okcBn04tXVEvjqtU7ucDdOaJW2oj1d30HVfmfEES9d5WB/qn+a+rNR2dX5m9ae4CYEbU3bqIVmN4qORhRtDVX7hDjqnOgfxyZ7c=
